// This copy is fixed and intentionally NOT generated by the LLM. The backend
// only ever tells us `category === "crisis"` — every word shown here is
// written and reviewed by a human, on purpose, so it can be checked for
// accuracy and tone directly in this file rather than trusted to a model.
//
// Helplines verified as of 2026. If you change these, verify the numbers
// are still active before shipping — this is the one part of the app where
// being wrong actually hurts someone.

type Resource = {
  name: string;
  detail: string;
  href: string;
};

const RESOURCES: Resource[] = [
  {
    name: "Tele MANAS",
    detail: "Govt. of India · 24/7 · call 14416 or 1-800-891-4416",
    href: "tel:14416",
  },
  {
    name: "Vandrevala Foundation",
    detail: "24/7 · call or WhatsApp +91 9999 666 555",
    href: "tel:+919999666555",
  },
  {
    name: "In immediate danger",
    detail: "Call India's national emergency number: 112",
    href: "tel:112",
  },
];

export default function CrisisPanel({ onReset }: { onReset: () => void }) {
  return (
    <div
      role="region"
      aria-label="Support resources"
      className="flex flex-col gap-8 border border-line bg-background-raised p-8 sm:p-12"
    >
      <div className="flex flex-col gap-3">
        <span className="font-mono text-xs uppercase tracking-[0.3em] text-calm">
          Before anything else
        </span>
        <h2 className="font-display text-2xl font-bold leading-snug text-foreground sm:text-3xl">
          What you wrote sounds like it might be more than a complaint.
        </h2>
        <p className="max-w-xl font-mono text-sm leading-relaxed text-muted">
          We&apos;re not going to joke about this one. If you&apos;re going
          through something difficult right now, you deserve real support —
          not a courtroom bit. You&apos;re not alone, and help is available,
          right now, for free.
        </p>
      </div>

      <div className="flex flex-col gap-px border border-line bg-line sm:grid sm:grid-cols-3 sm:gap-px">
        {RESOURCES.map((resource) => (
          <a
            key={resource.name}
            href={resource.href}
            className="flex flex-col gap-2 bg-background-raised p-5 transition-colors hover:bg-background"
          >
            <span className="font-condensed text-lg tracking-wide text-foreground">
              {resource.name}
            </span>
            <span className="font-mono text-xs leading-relaxed text-muted">
              {resource.detail}
            </span>
          </a>
        ))}
      </div>

      <p className="font-mono text-xs leading-relaxed text-muted">
        Outside India? Please contact your local emergency number or search
        for a crisis helpline in your country — help is out there wherever
        you are.
      </p>

      <button
        type="button"
        onClick={onReset}
        className="w-fit border border-line px-5 py-3 font-mono text-xs uppercase tracking-widest text-muted transition-colors hover:border-calm hover:text-foreground"
      >
        Back
      </button>
    </div>
  );
}
